# Site settings
title: Mauricio Urraco
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jaeyoung Ju
user_description: I'm a developer from Republic of Korea, always searching for the next challenge.
user_title: Developer
email: jujy4315@gmail.com
instagram_username: _joojae
github_username:  JAEYOUNGJU

exclude: ['package.json', 'src' , 'node_modules']
